// Типы данных для результатов тестирования
export interface TestResult {
  id: string;
  userId: string;
  userName: string;
  userType: 'candidate' | 'employee';
  testId: string;
  testTitle: string;
  score: number;
  passingScore: number;
  isPassed: boolean;
  completedAt: string;
  department?: string;
  position?: string;
}

// Моковые данные для примера
export const mockTestResults: TestResult[] = [
  {
    id: 'r1',
    userId: '1',
    userName: 'Смирнов Дмитрий Константинович',
    userType: 'employee',
    testId: '1',
    testTitle: 'Тест на знание AutoCAD',
    score: 85,
    passingScore: 70,
    isPassed: true,
    completedAt: '2025-04-15T14:30:00',
    department: 'Конструкторский отдел',
    position: 'Инженер-конструктор',
  },
  {
    id: 'r2',
    userId: '2',
    userName: 'Петрова Анна Сергеевна',
    userType: 'employee',
    testId: '2',
    testTitle: 'Тест на знание строительных норм и правил',
    score: 92,
    passingScore: 80,
    isPassed: true,
    completedAt: '2025-04-14T10:45:00',
    department: 'Технический отдел',
    position: 'Ведущий инженер',
  },
  {
    id: 'r3',
    userId: '1',
    userName: 'Сидоров Алексей Петрович',
    userType: 'candidate',
    testId: '1',
    testTitle: 'Тест на знание AutoCAD',
    score: 65,
    passingScore: 70,
    isPassed: false,
    completedAt: '2025-04-13T15:20:00',
    position: 'Инженер-конструктор',
  },
  {
    id: 'r4',
    userId: '2',
    userName: 'Козлова Екатерина Владимировна',
    userType: 'candidate',
    testId: '3',
    testTitle: 'Тест на знание Revit',
    score: 88,
    passingScore: 70,
    isPassed: true,
    completedAt: '2025-04-12T16:15:00',
    position: 'Архитектор',
  },
  {
    id: 'r5',
    userId: '3',
    userName: 'Соколов Дмитрий Александрович',
    userType: 'employee',
    testId: '5',
    testTitle: 'Тест на знание BIM-координации',
    score: 95,
    passingScore: 75,
    isPassed: true,
    completedAt: '2025-04-11T09:30:00',
    department: 'BIM-отдел',
    position: 'BIM-координатор',
  },
  {
    id: 'r6',
    userId: '3',
    userName: 'Новиков Игорь Михайлович',
    userType: 'candidate',
    testId: '2',
    testTitle: 'Тест на знание строительных норм и правил',
    score: 75,
    passingScore: 80,
    isPassed: false,
    completedAt: '2025-04-10T11:45:00',
    position: 'Инженер по надзору',
  },
  {
    id: 'r7',
    userId: '4',
    userName: 'Морозова Светлана Игоревна',
    userType: 'employee',
    testId: '4',
    testTitle: 'Психологический тест для руководителей',
    score: 82,
    passingScore: 60,
    isPassed: true,
    completedAt: '2025-04-09T14:00:00',
    department: 'Технический отдел',
    position: 'Руководитель проекта',
  },
  {
    id: 'r8',
    userId: '4',
    userName: 'Волков Максим Степанович',
    userType: 'candidate',
    testId: '1',
    testTitle: 'Тест на знание AutoCAD',
    score: 78,
    passingScore: 70,
    isPassed: true,
    completedAt: '2025-04-08T15:30:00',
    position: 'Инженер-проектировщик',
  },
  {
    id: 'r9',
    userId: '1',
    userName: 'Смирнов Дмитрий Константинович',
    userType: 'employee',
    testId: '3',
    testTitle: 'Тест на знание Revit',
    score: 80,
    passingScore: 70,
    isPassed: true,
    completedAt: '2025-04-07T10:15:00',
    department: 'Конструкторский отдел',
    position: 'Инженер-конструктор',
  },
  {
    id: 'r10',
    userId: '1',
    userName: 'Сидоров Алексей Петрович',
    userType: 'candidate',
    testId: '3',
    testTitle: 'Тест на знание Revit',
    score: 72,
    passingScore: 70,
    isPassed: true,
    completedAt: '2025-04-06T13:45:00',
    position: 'Инженер-конструктор',
  },
];
