[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd server && npm ci --omit=dev',
  'cd server && npx prisma generate'
]

[phases.build]
cmds = ['cd server && npm run build']

[start]
cmd = 'cd server && npm run start:prod' 