[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'echo "DATABASE_URL=postgresql://postgres:tcHTDfzKOwYTWbiZjrjImmkwOfUWaCwS@postgres.railway.internal:5432/railway" > .env && echo "JWT_SECRET=super-secret-key-123" >> .env && echo "NODE_ENV=production" >> .env && echo "PORT=8080" >> .env && echo "CORS_ORIGIN=https://nngp.vercel.app" >> .env && npx prisma migrate deploy && npm run seed && npm run start:prod' 