[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd server && npm ci',
  'cd server && npx prisma generate'
]

[phases.build]
cmds = ['cd server && npm run build']

[start]
cmd = 'node /app/server/dist/main' 